# Drupal 8 with PostgreSQL installed on subdirectory
#
# Access via "http://localhost:8080/<subdirectory name>" (or "http://$(docker-machine ip):8080/<subdirectory name>" if using docker-machine)
#

version: '3.1'

services:
  subdir-drupal:
    build:
      context: .
      dockerfile: drupal/Dockerfile
      args:
        # To change subdirectory name
        subdir_name: drupal
    ports:
      - 8080:80
    # Map volumes if you need it in local, add the files content first from the drupal docker image
    # volumes:
    #   - ./drupal/modules:/var/www/html/drupal/modules
    #   - ./drupal/profiles:/var/www/html/drupal/profiles
    #   - ./drupal/themes:/var/www/html/drupal/themes
    #   - ./drupal/sites:/var/www/html/drupal/sites
    restart: always

  postgres:
    image: postgres:10
    environment:
      # To change database password
      POSTGRES_PASSWORD: abc123456
    volumes:
        - ./postgresql/db_data:/var/lib/postgresql/data
    restart: always

